[profile.default]
src = "src"
out = "out"
libs = ["lib"]
"openzeppelin-contracts" = "github:OpenZeppelin/openzeppelin-contracts"
solc-version = "0.8.26"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
